# Generated by Django 5.1.5 on 2025-02-03 18:48

import datetime
import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Obrigatório. 14 caracteres no formato XXX.XXX.XXX-XX', max_length=150, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(default='Nome não informado', max_length=150)),
                ('cpf', models.CharField(max_length=30, unique=True)),
                ('telefone', models.CharField(blank=True, default='Telefone não informado', max_length=30)),
                ('data_nascimento', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Data de nascimento')),
                ('bairro', models.CharField(blank=True, default='Bairro não informado', max_length=255)),
                ('rua', models.CharField(blank=True, default='Rua não informada', max_length=255)),
                ('complemento', models.CharField(blank=True, default='complemento não informado', max_length=255)),
                ('numerocasa', models.CharField(default='Numero da Casa não informado', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
