# Generated by Django 5.1.5 on 2025-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numerocasa',
            field=models.CharField(default='Numero da Casa não informado', max_length=255),
        ),
    ]
