# Generated by Django 5.1.5 on 2025-01-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, default='Bairro não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, default='complemento não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rua',
            field=models.CharField(blank=True, default='Rua não informada', max_length=255),
        ),
    ]
