# Generated by Django 5.1.6 on 2025-02-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_bairro_alter_usuario_complemento_and_more'),
        ('users', '0002_alter_usuario_numerocasa'),
    ]

    operations = [
    ]
