# Generated by Django 5.1.6 on 2025-02-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250218_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
