# Generated by Django 5.1.4 on 2025-01-09 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao_prioritaria', models.CharField(choices=[('nenhuma', 'Não possui condição'), ('gravidez', 'Gravidez (Gestante)'), ('idoso', 'Idoso (60 anos ou mais)'), ('doencas_cronicas', 'Doenças Crônicas Graves'), ('urgencia', 'Urgências e Emergências'), ('deficiencia', 'Deficiências Físicas ou Mentais'), ('imunossupresso', 'Pacientes Imunossuprimidos'), ('doencas_infectocontagiosas', 'Doenças Infectocontagiosas')], default='nenhuma', max_length=50)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('nomeCompleto', models.CharField(max_length=40)),
                ('cartaoSaude', models.IntegerField(max_length=15)),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('idade', models.IntegerField(max_length=3)),
                ('telefone', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=25)),
                ('rua', models.CharField(max_length=45)),
                ('num_casa', models.IntegerField(max_length=6)),
                ('complemento', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
    ]
