# Generated by Django 5.1.4 on 2025-01-21 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_saude', models.IntegerField(unique=True)),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('condicao_prioritaria', models.CharField(blank=True, choices=[('nenhuma', 'Não possui condição'), ('gravidez', 'Gravidez (Gestante)'), ('idoso', 'Idoso (60 anos ou mais)'), ('doencas_cronicas', 'Doenças Crônicas Graves'), ('urgencia', 'Urgências e Emergências'), ('deficiencia', 'Deficiências Físicas ou Mentais'), ('imunossupresso', 'Pacientes Imunossuprimidos'), ('doencas_infectocontagiosas', 'Doenças Infectocontagiosas')], default='nenhuma', max_length=50, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
