<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-09 18:58

import django.core.validators
=======
# Generated by Django 5.1.4 on 2025-01-21 19:40

import django.db.models.deletion
from django.conf import settings
>>>>>>> 3051aee9c0858b89d2513a603c47cd992e1a3a54
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 3051aee9c0858b89d2513a603c47cd992e1a3a54
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('condicao_prioritaria', models.CharField(choices=[('nenhuma', 'Não possui condição'), ('gravidez', 'Gravidez (Gestante)'), ('idoso', 'Idoso (60 anos ou mais)'), ('doencas_cronicas', 'Doenças Crônicas Graves'), ('urgencia', 'Urgências e Emergências'), ('deficiencia', 'Deficiências Físicas ou Mentais'), ('imunossupresso', 'Pacientes Imunossuprimidos'), ('doencas_infectocontagiosas', 'Doenças Infectocontagiosas')], default='nenhuma', max_length=50)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('nomeCompleto', models.CharField(max_length=40)),
                ('cartaoSaude', models.IntegerField(max_length=15)),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('idade', models.IntegerField(max_length=3)),
                ('telefone', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=25)),
                ('rua', models.CharField(max_length=45)),
                ('num_casa', models.IntegerField(max_length=6)),
                ('complemento', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=30)),
=======
                ('cartao_saude', models.IntegerField(unique=True)),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('condicao_prioritaria', models.CharField(blank=True, choices=[('nenhuma', 'Não possui condição'), ('gravidez', 'Gravidez (Gestante)'), ('idoso', 'Idoso (60 anos ou mais)'), ('doencas_cronicas', 'Doenças Crônicas Graves'), ('urgencia', 'Urgências e Emergências'), ('deficiencia', 'Deficiências Físicas ou Mentais'), ('imunossupresso', 'Pacientes Imunossuprimidos'), ('doencas_infectocontagiosas', 'Doenças Infectocontagiosas')], default='nenhuma', max_length=50, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 3051aee9c0858b89d2513a603c47cd992e1a3a54
            ],
        ),
    ]
