# Generated by Django 5.1.5 on 2025-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='condicao_prioritaria',
            field=models.CharField(choices=[('nenhuma', 'Não possui condição'), ('gravidez', 'Gravidez (Gestante)'), ('idoso', 'Idoso (60 anos ou mais)'), ('doencas_cronicas', 'Doenças Crônicas Graves'), ('urgencia', 'Urgências e Emergências'), ('deficiencia', 'Deficiências Físicas ou Mentais'), ('imunossupresso', 'Pacientes Imunossuprimidos'), ('doencas_infectocontagiosas', 'Doenças Infectocontagiosas')], default='nenhuma', max_length=50),
        ),
    ]
