# Generated by Django 5.1.4 on 2025-01-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='num_casa',
            field=models.IntegerField(),
        ),
    ]
