# Generated by Django 5.1.6 on 2025-02-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_alter_paciente_condicao_prioritaria'),
        ('Unidade_Saude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='unidade_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Unidade_Saude.unidadesaude'),
        ),
    ]
