# Generated by Django 5.1.4 on 2025-01-21 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_alter_paciente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Data de nascimento'),
        ),
    ]
