# Generated by Django 5.1.4 on 2025-01-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_alter_paciente_idade_alter_paciente_num_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cartaoSaude',
            field=models.IntegerField(),
        ),
    ]
