# Generated by Django 5.1.4 on 2025-01-22 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0003_alter_paciente_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
    ]
