# Generated by Django 5.1.4 on 2025-01-10 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0002_rename_datafinal_campanha_data_final_and_more'),
        ('Paciente', '0003_alter_paciente_cartaosaude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nomeCompleto',
            new_name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cartaoSaude',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idade',
        ),
        migrations.AddField(
            model_name='paciente',
            name='campanhas',
            field=models.ManyToManyField(blank=True, to='Campanha.campanha'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cartao_saude',
            field=models.IntegerField(default=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
    ]
