# Generated by Django 5.1.4 on 2025-01-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0004_rename_nomecompleto_paciente_nome_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='condicao_prioritaria',
            field=models.CharField(blank=True, choices=[('nenhuma', 'Não possui condição'), ('gravidez', 'Gravidez (Gestante)'), ('idoso', 'Idoso (60 anos ou mais)'), ('doencas_cronicas', 'Doenças Crônicas Graves'), ('urgencia', 'Urgências e Emergências'), ('deficiencia', 'Deficiências Físicas ou Mentais'), ('imunossupresso', 'Pacientes Imunossuprimidos'), ('doencas_infectocontagiosas', 'Doenças Infectocontagiosas')], default='nenhuma', max_length=50, null=True),
        ),
    ]
