services:
  - type: web
    name: agendmed
    env: python
    buildCommand: |
      echo "1. Instalando dependências..."
      pip install -r requirements.txt
      
      echo "2. Verificando banco de dados..."
      python wait_for_db.py || exit 1
      
      echo "3. Verificando migrações aplicadas..."
      python manage.py showmigrations
      
      echo "4. Coletando arquivos estáticos..."
      python manage.py collectstatic --noinput
      
      echo "✅ Deploy concluído com sucesso!"
    envVars:
      - key: DATABASE_URL
        value: postgresql://agendmed_user:UAOYpOYCBi1Xz7XDkUO2exKlH9CAuwV8@dpg-d20lqr7gi27c73cp1dag-a.oregon-postgres.render.com:5432/agendmed_postgresql
      - key: DEBUG
        value: 'True'
      - key: DISABLE_COLLECTSTATIC
        value: '1'