services:
  - type: web
    name: agendmed
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python wait_for_db.py
      echo ">>> Executando makemigrations..."
      python manage.py makemigrations --noinput
      echo ">>> Executando migrate..."
      python manage.py migrate --noinput
      echo ">>> Verificando migrações aplicadas..."
      python manage.py showmigrations
      python manage.py collectstatic --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: AgendMed.settings
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: agendmed_postgresql
          property: connectionString
