services:
  - type: web
    name: agendmed
    env: python
    buildCommand: |

      echo "1. Instalando dependências..."
      pip install -r requirements.txt
      
      echo "2. Verificando conexão com o banco..."
      python check_db.py || exit 1
      
      echo "3. Aplicando migrações..."
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      
      echo "4. Verificando migrações..."
      python manage.py showmigrations
      
      echo "5. Coletando arquivos estáticos..."
      python manage.py collectstatic --noinput
      
      echo "✅ Deploy concluído com sucesso!"