services:
  - type: web
    name: agendmed
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn AgendMed.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: AgendMed.settings
      - key: PYTHON_VERSION
        value: "3.11"
