services:
  - type: web
    name: agendmed
    env: python
    buildCommand: |
      echo "1. Instalando dependências..."
      pip install -r requirements.txt
      
      echo "2. Forçando migrações..."
      python force_migrate.py || exit 1
      
      echo "3. Coletando estáticos..."
      python manage.py collectstatic --noinput
      
      echo "✅ Build completo!"