services:
  - type: web
    name: agendmed
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python wait_for_db.py
      python manage.py makemigrations --no-input
      python manage.py migrate --no-input
      python manage.py collectstatic --no-input
    startCommand: gunicorn AgendMed.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: AgendMed.settings
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: agendmed_postgresql
          property: connectionString
