services:
  - type: web
    name: agendmed
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    envVars:
      - key: DATABASE_URL
        value: postgresql://agendmed_user:Lnz3f70OOWdvB9tDPVwcAh4ABYxkpBe8@dpg-d22134vdiees73e9tchg-a.oregon-postgres.render.com:5432/agendmed
      - key: DISABLE_COLLECTSTATIC
        value: '1'
      - key: DEBUG
        value: 'False' 