<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-10 15:08
=======
# Generated by Django 5.1.4 on 2025-01-21 17:58
>>>>>>> 3051aee9c0858b89d2513a603c47cd992e1a3a54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unidade_Saude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nome', models.CharField(max_length=100)),
=======
>>>>>>> 3051aee9c0858b89d2513a603c47cd992e1a3a54
                ('especialidade', models.CharField(max_length=50)),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='Unidade_Saude.unidadesaude')),
            ],
        ),
    ]
