# Generated by Django 5.1.5 on 2025-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalsaude',
            name='ativo',
            field=models.BooleanField(default=False, help_text='Indica se o profissional está ativo no sistema', verbose_name='Ativo'),
        ),
    ]
