# Generated by Django 5.1.4 on 2025-01-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]


        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Bairro',
            field=models.TextField(blank=True, default='Bairro não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='NumeroCasa',
            field=models.CharField(default='Numero da Casa não informado', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Rua',
            field=models.TextField(blank=True, default='Rua não informada', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.TextField(blank=True, default='complemento não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_Completo',
            field=models.CharField(default='Nome não informado', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default='Telefone não informado', max_length=30),
        ),
    ]
