# Generated by Django 5.1.4 on 2025-01-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nomeCompleto',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(default='Nome não informado', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.TextField(blank=True, default='Endereço não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default='Telefone não informado', max_length=30),
        ),
    ]
