# Generated by Django 5.1.4 on 2025-01-21 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuario_nomecompleto_usuario_nome_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        
        migrations.AddField(
            model_name='usuario',
            name='Bairro',
            field=models.TextField(blank=True, default='Bairro não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='NumeroCasa',
            field=models.CharField(default='Numero da Casa não informado', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Rua',
            field=models.TextField(blank=True, default='Rua não informada', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.TextField(blank=True, default='complemento não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dataNascimento',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
