# Generated by Django 5.1.4 on 2025-01-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
                ('dataInicial', models.DateField()),
                ('dataFinal', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
            ],
        ),
    ]
