# Generated by Django 5.1.5 on 2025-02-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unidade_Saude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=150)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='campanhas/')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('unidade_saude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='Unidade_Saude.unidadesaude')),
            ],
            options={
                'permissions': [('pode_cadastrar_campanha', 'Pode cadastrar campanhas')],
            },
        ),
    ]
