# Generated by Django 5.1.4 on 2025-01-10 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0001_initial'),
        ('Unidade_Saude', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campanha',
            old_name='dataFinal',
            new_name='data_final',
        ),
        migrations.RenameField(
            model_name='campanha',
            old_name='dataInicial',
            new_name='data_inicial',
        ),
        migrations.AddField(
            model_name='campanha',
            name='unidade_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='Unidade_Saude.unidadesaude'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='campanhas/'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
