<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-10 15:08
=======
# Generated by Django 5.1.4 on 2025-01-21 19:43
>>>>>>> 3051aee9c0858b89d2513a603c47cd992e1a3a54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('Paciente', '0004_rename_nomecompleto_paciente_nome_completo_and_more'),
        ('Profissional', '0001_initial'),
=======
        ('Paciente', '0001_initial'),
        ('Profissional', '0002_initial'),
>>>>>>> 3051aee9c0858b89d2513a603c47cd992e1a3a54
        ('Unidade_Saude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('fichas_normais', models.IntegerField(default=0)),
                ('fichas_prioridade', models.IntegerField(default=0)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='Paciente.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='Profissional.profissionalsaude')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='Unidade_Saude.unidadesaude')),
            ],
        ),
    ]
