# Generated by Django 5.1.5 on 2025-01-23 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
        ('Profissional', '0001_initial'),
        ('Unidade_Saude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('fichas_normais', models.IntegerField(default=0)),
                ('fichas_prioridade', models.IntegerField(default=0)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='Paciente.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='Profissional.profissionalsaude')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='Unidade_Saude.unidadesaude')),
            ],
        ),
    ]
