# Generated by Django 5.1.5 on 2025-02-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaConsulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'permissions': [('pode_agendar_consulta', 'Pode agendar consultas'), ('pode_gerenciar_consultas', 'Pode gerenciar consultas'), ('pode_atender', 'Pode atender pacientes')]},
        ),
    ]
