# Generated by Django 5.1.6 on 2025-02-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaConsulta', '0002_alter_consulta_options'),
        ('Paciente', '0002_alter_paciente_condicao_prioritaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='numero_na_fila',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='Paciente.paciente')),
            ],
        ),
    ]
