# Generated by Django 5.1.6 on 2025-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaConsulta', '0003_consulta_numero_na_fila_notificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='numero_na_fila',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='numero_na_fila',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
