# Generated by Django 5.1.6 on 2025-03-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaConsulta', '0004_remove_consulta_numero_na_fila_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('domiciliar', 'Consulta Domiciliar'), ('comum', 'Consulta Comum (Posto de Saúde)')], default='comum', max_length=15),
        ),
    ]
